version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      DEFAULT_TAGS: "Спорт,Политика,Культура,Наука,Искусство,Технологии,Путешествия,Еда,Мода,Здоровье,Гейминг" 
      POSTGRES_PORT: 5432
      BASE_URL: http://localhost:8000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    environment:
      VUE_APP_API_BASE_URL: http://backend
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
